# Generated by Django 3.2.9 on 2021-12-13 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shoppinglistdetails',
            name='product',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='ShoppingListDetails',
        ),
    ]
